apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm-test
  namespace: argocd
spec:
  destination:
    namespace: argo-test
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/shubhamrai1993/argo-repo
    path: .
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
