apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.nginx.com/stable'
    targetRevision: 0.12.1
    chart: nginx-ingress
    helm:
      values: |-
        controller:
          pod:
            annotations:
              test-key: {{ .Values.podLabel }}
  project: default
  syncPolicy:
    automated: {}
